<?php

function islandora_pageCmodel_search_preprocess_islandora_solr(&$variables) {
  $results = $variables['results'];
  if (module_exists('islandora_collection_toggle_publish')) {
    module_load_include('module', 'islandora_collection_toggle_publish');
    foreach ($results as $key => $result) {
      $obj = islandora_object_load($result['PID']);
      if (grant_access($obj)) {
        $replaced = replace_label_for_pages($result);
        if (isset($variables['results'][$key]['solr_doc'])) {
          $variables['results'][$key]['solr_doc']['mods_titleInfo_title_ms']['value'] = $replaced;
        }
      }
    }
  }
}

function replace_label_for_pages($result) {
  $bookpage = in_array("info:fedora/islandora:pageCModel", $result['content_models']);
  $newspage = in_array("info:fedora/islandora:newspaperPageCModel", $result['content_models']);
  if ($newspage || $bookpage) {
    $object = islandora_object_load($result['PID']);
    $sequence = $object->relationships->get('http://islandora.ca/ontology/relsext#', 'isSequenceNumber');
    //use relationships to get page number
    $label = $object->label;
    $parent = $object->getParents(0);
    //last $parent wins. not ideal in edge case of two parent objects
    $parent = islandora_object_load($parent[0]);
    $page =  ': Page ' . $sequence[0]['object']['value'];;
    $text  = $parent->label;
    $replaced = preg_replace('#(<a.*?>).*?(</a>)#', "$1$label$2", "$text$page");
    return $replaced;
  }
  else {
    return $result['solr_doc']['mods_titleInfo_title_ms']['value'];
  }
}
